spring:
  profiles:
    include: gt-core

#mybatis配置文件
mybatis:
  #  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mybatis/*.xml



#server:
#  ssl:
#    key-store: gt.keystore
#    key-alias: gtkey
#    key-store-password: guting
#    key-store-type: JKS
#    enabled: true
